name = "hayaa"
compatibility_date = "2025-05-06"
workers_dev        = true

compatibility_flags = ["nodejs_compat"]
main               = "api/worker.js"

[build]
  command = "npm ci"

# Tell Rollup to leave `ws` imports unresolved
[build.rollupOptions]
  external = ["ws"]

[vars]
  CLOUDINARY_URL         = "cloudinary://995673441211498:N-EuJC-I7BNexpB7toFMfoBQ9SM@dwk5eorvm"
  CLOUDINARY_CLOUD_NAME  = "dwk5eorvm"
  CLOUDINARY_API_KEY     = "995673441211498"
  CLOUDINARY_API_SECRET  = "N-EuJC-I7BNexpB7toFMfoBQ9SM"
  MONGODB_URI            = "mongodb://hayaAdmin:coins225@localhost:27017/haya"
  CLIENT_URL             = "http://localhost:5173"
  JWT_SECRET             = "8d89cd31faf25adb3c21901b0abed0efac4ec8bd3355510f42b051a4c9d76d58943ae026550f34ccc4be6e80e68aa09baa26a978905634cc2969e46850ce90e2"
  NODE_ENV               = "production"
  PORT                   = "5000"
